Feature/pagination filtration sorting
AndrianovaVeronika/clockwise_clockware_frontend pull request #11
Opened 2022-10-13 02:39 UTC by AndrianovaVeronika

2022-10-13 12:49 UTC, nik-clockwise requested changes

2022-10-13 12:49 UTC, nik-clockwise commented on src/store/actions/users.js
> +    getFiltered: getFilteredUsers,
Обчно делают не обязательный параметр в метод all и не создают отдельный.
Еще в таком подходе непонятно откуда вообще берутся данные для фильтра, магия какая-то

2022-10-13 12:49 UTC, nik-clockwise commented on src/store/initialState.js
> +        ordersFilteredList: [],
Получается много лишнего/дублирующегося кода

2022-10-13 12:49 UTC, nik-clockwise commented on src/store/selectors/citiesSelector.js
> +export const getFilteredCitiesSelector = createSelector((state) => state.cities, (state) => state.cities.citiesFilteredList);
Надо это всё зарефакторить что бы методы all принимали фильтр и всё работало ок

2022-10-13 13:03 UTC, AndrianovaVeronika commented on src/store/actions/users.js
> +    getFiltered: getFilteredUsers,
Это просто объект, который принимает в себя actions. Так можно использовать в шаблонных компонентах.

2022-10-13 13:04 UTC, AndrianovaVeronika commented on src/store/initialState.js
> +        ordersFilteredList: [],
Я не могу отнести это в один лист так как мне нужен отсортированный и неотсортированный одновременно

2022-10-13 13:10 UTC, AndrianovaVeronika commented on src/store/selectors/citiesSelector.js
> +export const getFilteredCitiesSelector = createSelector((state) => state.cities, (state) => state.cities.citiesFilteredList);
Это селекторы, они просто достают списки из стора. Для самих методов есть actionApi с методом GET_FILTERED, который возвращает функцию принимающую фильтры.

2022-10-13 13:24 UTC, nik-clockwise commented on src/store/initialState.js
> +        ordersFilteredList: [],
А это как? Зачем нам все посты, если мы фильтруем посты? 2 запроса на бек, когда можно обойтись одним

2022-10-13 13:26 UTC, nik-clockwise commented on src/store/selectors/citiesSelector.js
> +export const getFilteredCitiesSelector = createSelector((state) => state.cities, (state) => state.cities.citiesFilteredList);
Я так понимаю, что в апи должен быть один метод getCities() а принимать он удет фильтры и пагинационные параметры

2022-10-21 10:13 UTC, nik-clockwise requested changes

2022-10-21 10:13 UTC, nik-clockwise commented on src/components/DataTables/CitiesTable/index.js
> +        setRows(await getAllCities());
А тут все города выбираем, внутри есть пагинация? Выбирается часть городов из базы или все?

2022-10-21 10:13 UTC, nik-clockwise commented on src/components/DataTables/CitiesTable/index.js
> +        setRows(await getAllCities());
Надо часть, т.к. все записи брать нельзя, когда их 1миллион то будет очень тяжело

2022-10-21 10:13 UTC, nik-clockwise commented on src/components/DataTables/MastersTable/index.js
> +        setRows(await getAllMasters());
Вопрос тот же, что с количеством записей

2022-10-21 12:11 UTC, merged