Feature/user master orders page
AndrianovaVeronika/clockwise_clockware_frontend pull request #2
Opened 2022-09-07 23:43 UTC by AndrianovaVeronika

2022-09-08 19:59 UTC, nik-clockwise requested changes

2022-09-08 19:59 UTC, nik-clockwise commented on src/components/Forms/UserForms/OrderForm/CredentialsForm.js
> +    const onSubmit = async (v, props) => {
async тут не нужен получается, либо надо await submitAction надо

2022-09-08 19:59 UTC, nik-clockwise commented on src/store/middleware/createActionApi.js
> -                        'x-access-token': sessionStorage.getItem('TOKEN')
Установку базовых заголовуков можно собрать в одном месте, установив один раз дефолтный  заголовок для клиента, так будет на много лучше, читаемей и меньше дублирующегося кода

2022-09-09 00:08 UTC, AndrianovaVeronika commented on src/components/Forms/UserForms/OrderForm/CredentialsForm.js
> +    const onSubmit = async (v, props) => {
Убрала

2022-09-09 00:16 UTC, AndrianovaVeronika commented on src/store/middleware/createActionApi.js
> -                        'x-access-token': sessionStorage.getItem('TOKEN')
Добавила store/middleware/headers

2022-09-09 10:27 UTC, nik-clockwise approved these changes

2022-09-09 10:41 UTC, merged